---
title: "Project"
output: html_document
date: "2022-11-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                      error = TRUE)
                
library(tidyverse)
library(lubridate)
library(kableExtra)
library(readxl)
library(ggplot2)
library(maps)
library(ggridges)

state = data.frame(state = state.abb, region = state.region, 
                   state_name = tolower(state.name))

year_2003 = read_excel("FY2003_50Rents_County.xls") %>% 
    select(state = State_Alpha, rent_03 = rent50_3) %>% 
  inner_join(state) %>% 
  group_by(state, region) %>% 
    summarize(rent_03 = round(mean(rent_03),2)) %>% 
  mutate(year_03 = "2003")

year_2008 = read_excel("FY2008_county_level_50th_r.xls") %>% 
  select(state = state_alpha, rent_08 = Rent50_3) %>%  
  inner_join(state) %>% 
    group_by(state, region) %>% 
    summarize(rent_08 = round(mean(rent_08),2))%>% 
  mutate(year_08 = "2008")

year_2013 = read_excel("FY2013_50_Final.xls")  %>% 
  select(state = state_alpha, rent_13 = Rent50_3) %>%  
  inner_join(state) %>% 
    group_by(state, region) %>% 
    summarize(rent_13 = round(mean(rent_13),2)) %>% 
  mutate(year_13 = "2013")

year_2018 = read_excel("FY2018_50_County_rev.xlsx") %>% 
  select(state = state_alpha, rent_18 = rent50_3) %>%  
  inner_join(state) %>% 
    group_by(state, region) %>% 
    summarize(rent_18 = round(mean(rent_18),2)) %>% 
  mutate(year_18 = "2018")

year_2023 = read_excel("FY2023_FMR_50_county.xlsx") %>% 
  select(state = state_alpha, rent_23 = rent_50_3) %>%  
  inner_join(state) %>% 
    group_by(state, region) %>% 
    summarize(rent_23 = round(mean(rent_23),2)) %>% 
  mutate(year_23 = "2023")

years = year_2023 %>%  full_join(year_2018) %>% full_join(year_2013) %>% full_join(year_2008) %>% full_join(year_2003) %>% 
  select(state, starts_with("r")) %>% 
    pivot_longer(
        cols = starts_with("rent"),
        names_to = "year",
        values_to = "rent")
years[years == "rent_23"] = "2023"
years[years == "rent_18"] = "2018"
years[years == "rent_13"] = "2013"
years[years == "rent_08"] = "2008"
years[years == "rent_03"] = "2003"
```

## R Markdown

```{r}
ggplot(years, aes(x = state, y = rent)) +
  geom_point(size = 2, color = "red") + 
  geom_segment(aes(x = state, xend = state, y = 0, yend = rent)) +
  facet_grid(vars(year)) +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
    labs(x = "State", y = "Rent Price",  
         title = "Rent Prices by State", subtitle = "3 Bedrooms") 

year_2003 = year_2003 %>%  full_join(state)
states = map_data("state") %>% mutate(state_name = region)    
map = merge(states, year_2003, by = "state_name", all.x = T)  
map_03 = map[order(map$order), ]     
ggplot(map_03, aes(x = long, y = lat, group = group)) +  
    geom_polygon(aes(fill = rent_03)) +   
    geom_path() + 
    scale_fill_gradientn(colors = rev(heat.colors(10))) +
    coord_map() +
    labs(x = "Longitude", y = "Latitude", 
         title = "Rent Prices by State", 
         subtitle = "3 Bedrooms in 2003") +
    guides(fill = guide_legend(title = "Rent Price")) +
  theme_ridges()

year_2008 = year_2008 %>%  full_join(state)
states = map_data("state") %>% mutate(state_name = region)    
map = merge(states, year_2008, by = "state_name", all.x = T)  
map_08 = map[order(map$order), ]     
ggplot(map_08, aes(x = long, y = lat, group = group)) +  
    geom_polygon(aes(fill = rent_08)) +   
    geom_path() + 
    scale_fill_gradientn(colors = rev(heat.colors(10))) +
    coord_map() +
    labs(x = "Longitude", y = "Latitude", 
         title = "Rent Prices by State", 
         subtitle = "3 Bedrooms in 2008") +
    guides(fill = guide_legend(title = "Rent Price")) +
  theme_ridges()

year_2013 = year_2013 %>%  full_join(state)
states = map_data("state") %>% mutate(state_name = region)    
map = merge(states, year_2013, by = "state_name", all.x = T)  
map_13 = map[order(map$order), ]     
ggplot(map_13, aes(x = long, y = lat, group = group)) +  
    geom_polygon(aes(fill = rent_13)) +   
    geom_path() + 
    scale_fill_gradientn(colors = rev(heat.colors(10))) +
    coord_map() +
    labs(x = "Longitude", y = "Latitude", 
         title = "Rent Prices by State", 
         subtitle = "3 Bedrooms in 2013") +
    guides(fill = guide_legend(title = "Rent Price")) +
  theme_ridges()

year_2018 = year_2018 %>%  full_join(state)
states = map_data("state") %>% mutate(state_name = region)    
map = merge(states, year_2018, by = "state_name", all.x = T)  
map_18 = map[order(map$order), ]     
ggplot(map_18, aes(x = long, y = lat, group = group)) +  
    geom_polygon(aes(fill = rent_18)) +   
    geom_path() + 
    scale_fill_gradientn(colors = rev(heat.colors(10))) +
    coord_map() +
    labs(x = "Longitude", y = "Latitude", 
         title = "Rent Prices by State", 
         subtitle = "3 Bedrooms in 2018") +
    guides(fill = guide_legend(title = "Rent Price")) +
  theme_ridges()

year_2023 = year_2023 %>%  full_join(state)
states = map_data("state") %>% mutate(state_name = region)    
map = merge(states, year_2023, by = "state_name", all.x = T)  
map_23 = map[order(map$order), ]     
ggplot(map_23, aes(x = long, y = lat, group = group)) +  
    geom_polygon(aes(fill = rent_23)) +   
    geom_path() + 
    scale_fill_gradientn(colors = rev(heat.colors(10))) +
    coord_map() +
    labs(x = "Longitude", y = "Latitude", 
         title = "Rent Prices by State", 
         subtitle = "3 Bedrooms in 2023") +
    guides(fill = guide_legend(title = "Rent Price")) +
  theme_ridges()


ggplot(year_2003, aes(x = rent_03, y = region, fill = region)) +
    geom_density_ridges() +
    theme_ridges() +                              
    theme(legend.position = "none",                  
          axis.title.x = element_text(hjust = 0.5),  
          axis.title.y = element_text(hjust = 0.5)) + 
    labs(x = "Rent Price", y = "Region",  
         title = "Rent Prices by Region", subtitle = "3 Bedrooms in 2003") 

ggplot(year_2003, aes(x = rent_03, fill = region)) + 
  geom_density(alpha = 0.3)+ 
    theme_ridges()+
    labs(x = "Rent Price", y = "Density",  
         title = "Rent Prices by Region", subtitle = "3 Bedrooms in 2003") +
    guides(fill = guide_legend(title = "Region"))  

ggplot(year_2003, aes(x = region, y = rent_03, fill = region)) + 
    geom_violin(trim = FALSE) + 
    geom_boxplot(width = 0.1) + 
    theme_ridges() +
    labs(x = "Region", y = "Rent Price",  
         title = "Rent Prices by Region", subtitle = "3 Bedrooms in 2003") +
    guides(fill = guide_legend(title = "Region")) 

ggplot(years, aes(x = rent, y = region, fill = region)) +
    geom_density_ridges() +
    facet_grid("year") +
    theme_ridges() +                              
    theme(legend.position = "none",                  
          axis.title.x = element_text(hjust = 0.5),  
          axis.title.y = element_text(hjust = 0.5)) + 
    labs(x = "Rent Price", y = "Region",  
         title = "Rent Prices by Region", subtitle = "3 Bedrooms") 

ggplot(year_2003, aes(region, rent_03)) + geom_boxplot() +  
    theme_ridges() +
    labs(x = "Region", y = "Rent Price",  
         title = "Rent Prices by Region", subtitle = "3 Bedrooms in 2003") 


ggplot(years,aes(year, rent)) + geom_boxplot() + 
    theme_ridges() +
    labs(x = "Year",  y = "Rent Price",
         title = "Rent Prices by Year", subtitle = "3 Bedrooms") 

ggplot(years,aes(rent,region)) + geom_boxplot() + facet_grid(vars(year)) +
    theme_ridges() +
    labs(x = "Rent Price", y = "Region",  
         title = "Rent Prices by Region", subtitle = "3 Bedrooms") 

ggplot(years,aes(year, rent)) + geom_boxplot() + facet_wrap(vars(region)) + 
    theme_ridges() +
    labs(x = "Year", y = "Rent Price",  
         title = "Rent Prices by Year and Region", subtitle = "3 Bedrooms")  
```
```{r}
library(maps)
library(ggplot2)
us.map <-  map_data('state')
# add PADD zones
us.map$PADD[us.map$region %in% 
          c("alabama","arkansas","delaware","florida","georgia","kentucky",'louisiana','maryland','mississippi','north carolina', 'oklahoma', 'south carolina', 'tennessee', 'texas', 'virginia','west virginia')] <- "PADD 1: South"
us.map$PADD[us.map$region %in% 
          c('alaska','arizona','california','colorado','hawaii','idaho','montana','nevada','new mexico','oregon','utah','washington','wyoming')] <- "PADD 2: West"
us.map$PADD[us.map$region %in% 
          c('connecticut','maine','massachusetts','new hampshire','new jersey','new york', 'pennsylvania','rhode island','vermont')] <- "PADD 3: Northeast"
us.map$PADD[us.map$region %in% 
          c('illinois','indiana','iowa','kansas','michigan','missouri','nebraska','north dakota','ohio','south dakota','wisconsin', 'minnesota')] <- "PADD 4: North Central"
us.map = us.map %>% 
  filter(region != 'district of columbia')
# subset the dataframe by padd zones and move lat/lon accordingly
us.map$lat.transp[us.map$PADD == "PADD 1: South"] <- us.map$lat[us.map$PADD == "PADD 1: South"] - 5
us.map$long.transp[us.map$PADD == "PADD 1: South"] <- us.map$long[us.map$PADD == "PADD 1: South"] - 4
us.map$lat.transp[us.map$PADD == "PADD 3: Northeast"] <- us.map$lat[us.map$PADD == "PADD 3: Northeast"] - 3
us.map$long.transp[us.map$PADD == "PADD 3: Northeast"] <- us.map$long[us.map$PADD == "PADD 3: Northeast"]
us.map$lat.transp[us.map$PADD == "PADD 4: North Central"] <- us.map$lat[us.map$PADD == "PADD 4: North Central"]
us.map$long.transp[us.map$PADD == "PADD 4: North Central"] <- us.map$long[us.map$PADD == "PADD 4: North Central"] - 5
us.map$lat.transp[us.map$PADD == "PADD 2: West"] <- us.map$lat[us.map$PADD == "PADD 2: West"] - 2
us.map$long.transp[us.map$PADD == "PADD 2: West"] <- us.map$long[us.map$PADD == "PADD 2: West"] - 10

# add labels
states <- aggregate(cbind(long.transp, lat.transp) ~ region, data=us.map, 
                FUN=function(x)mean(range(x)))
states$labels <- c("AL", "AR", "AZ", "CA", "CO", "CT", "DE", "FL", "GA", "IA", 
              "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", 
              "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", 
              "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", 
              "VT", "WA", "WI", "WV", "WY")
# plot and use padd zone as fill
ggplot(us.map,  aes(x=long.transp, y=lat.transp), colour="white") + 
  geom_polygon(aes(group = group, fill=PADD)) +
  geom_text(data=states, aes(long.transp, lat.transp, label=labels), size=3) +
  theme(panel.background = element_blank(),  # remove background
    panel.grid = element_blank(), 
    axis.line = element_blank(), 
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank()) +
  coord_equal() 
```
```
```{r}
pct_change <- function(start, final, perc = FALSE) {

  x <- ((final - start) / (abs(start))) * 100 

  x

}
```
